name: CI

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - &setup-node
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - &restore-modules
        name: Restore node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ${{ matrix.project }}/node_modules
          key: ${{ runner.os }}-${{ matrix.project }}-${{ hashFiles(format('{0}/package-lock.json', matrix.project)) }}
          restore-keys: ${{ runner.os }}-${{ matrix.project }}-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  build:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - *checkout
      - *setup-node
      - *restore-modules
      - name: Build
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - *checkout
      - *setup-node
      - *restore-modules
      - name: Test
        run: npm test

  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - *checkout
      - *setup-node
      - *restore-modules
      - name: Lint
        run: npm run lint

  typecheck:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - *checkout
      - *setup-node
      - *restore-modules
      - name: Type-check
        run: npm run tsc

